---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: apiportal
  namespace: apps
  annotations:
    hub.traefik.io/api-portal: portal
    kubernetes.io/ingress.class: back-layer
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`api-portal.${CLUSTERNAME}.${FULLDOMAINNAME}`)
    kind: Rule
    services:
    - name: apiportal
      namespace: traefik
      port: 9903
  tls:
    certResolver: le
