apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: forward-tls-option
  namespace: traefik
spec:
  sniStrict: true 
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: catchall-tcp-http
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: front-layer
spec:
  entryPoints:
    - web
  routes:
    - match: HostSNIRegexp(`[[:ascii:]]+\.${CLUSTERNAME}\.${DOMAINNAME}\.${TLD}`)
      priority: 999
      services:
        - name: traefik
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransportTCP
metadata:
  name: tls-transport
  namespace: traefik
spec:
  tls:
    insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: catchall-tcp-https
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: front-layer
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNIRegexp(`[[:ascii:]]+\.${CLUSTERNAME}\.${DOMAINNAME}\.${TLD}`)
      priority: 999
      services:
        - name: traefik
          port: 443
          serversTransport: tls-transport      
  tls:
    options:
      name: forward-tls-option
    passthrough: true
