---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingress-customers
  namespace: apps
  annotations:
    hub.traefik.io/api: customer-api-versioned
    hub.traefik.io/api-version: customer-api-v1
    kubernetes.io/ingress.class: back-layer
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.hub.${CLUSTERNAME}.${FULLDOMAINNAME}`) && PathPrefix(`/customers`)
      services:
        - name: customer-app
          port: 3000
      middlewares:
        - name: cors
  tls:
    certResolver: le
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: apps
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowMethods:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - CONNECT
      - OPTIONS
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 0
    accessControlAllowHeaders:
      - "*"